version: '2'

services:
    activemq:
        image: activemq
        build:
            context: ./activemq
            dockerfile: Dockerfile
        container_name: activemq_1
        ports:
            - "5672:5672"
            - "61616:61616"
            - "8161:8161"
        volumes:
            - activemq-vol:/mnt/nfs-share/activemq

    rabbitmq:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
            args:
                SSL_PASSWORD: password
        container_name: rabbitmq_1
        depends_on:
            - ssl-gen
        environment:
            - RABBITMQ_MNESIA_BASE=/mnt/rabbitmq/data/mnesia
        ports:
            - "5671:5671"
            - "5672:5672"
            - "8080:15672"
        volumes:
            - rabbitmq-vol:/mnt/rabbitmq/data
            - ssl-vol:/mnt/ssl
            - ./rabbitmq/:/mnt/rabbitmq/config/

    ssl-gen:
        build:
            context: ./ssl-gen
            dockerfile: Dockerfile
        container_name: ssl-gen_1
        environment:
            - SSL_PASSWORD=password
            - SERVER_SUBJ=/CN=rabbitmq/O=server/
            - CLIENT_SUBJ=/CN=rabbitmq/O=client/
        volumes:
            - ssl-vol:/mnt/ssl

volumes:
    activemq-vol:
        driver: local
    rabbitmq-vol:
        driver: local
    ssl-vol:
        driver: local
