version: '2'

services:
    activemq:
        build:
            context: ./activemq
            dockerfile: Dockerfile
        container_name: activemq_1
        image: activemq
        ports:
            - "5672:5672"
            - "61613:61613"
            - "61616:61616"
            - "8161:8161"
        volumes:
            - activemq-vol:/mnt/nfs-share/activemq

volumes:
    activemq-vol:
        driver: local
    nfs-vol:
        driver: local
