version: '2'

services:
    activemq:
        build:
            context: ./activemq
            dockerfile: Dockerfile
        container_name: activemq_1
        image: activemq
        ports:
            - "5672:5672"
            - "61616:61616"
            - "8161:8161"
        volumes:
            - activemq-vol:/mnt/nfs-share/activemq

    rabbitmq:
#        image: rabbitmq:3-management
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        container_name: rabbitmq_1
        environment:
#            - RABBITMQ_CONFIG_FILE=/mnt/rabbitmq/config/rabbitmq.config
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=user
            - RABBITMQ_MNESIA_BASE=/mnt/rabbitmq/data/mnesia
            - RABBITMQ_LOG_BASE=/mnt/rabbitmq/data/log
        ports:
            - "5672:5672"
            - "8080:15672"
        volumes:
            - rabbitmq-vol:/mnt/rabbitmq/data
            - ./rabbitmq/:/mnt/rabbitmq/config/
#        command:  bash -c "sleep 10; rabbitmq-server;"

volumes:
    activemq-vol:
        driver: local
    rabbitmq-vol:
        driver: local
