version: '2'

services:
    activemq:
        image: activemq
        build:
            context: ./activemq
            dockerfile: Dockerfile
        container_name: activemq_1
        ports:
            - "5672:5672"
            - "61616:61616"
            - "8161:8161"
        volumes:
            - activemq-vol:/mnt/nfs-share/activemq

    rabbitmq:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
            args:
                SSL_PASSWORD: password
        container_name: rabbitmq_1
        environment:
#            - RABBITMQ_CONFIG_FILE=/mnt/rabbitmq/config/rabbitmq.config
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_MNESIA_BASE=/mnt/rabbitmq/data/mnesia
            - RABBITMQ_LOG_BASE=/mnt/rabbitmq/data/log
        ports:
            - "5672:5672"
            - "8080:15672"
        volumes:
            - rabbitmq-vol:/mnt/rabbitmq/data
            - ./rabbitmq/:/mnt/rabbitmq/config/

volumes:
    activemq-vol:
        driver: local
    rabbitmq-vol:
        driver: local
